fix unbundling

diff --git a/bundle_header b/bundle_header
--- a/bundle_header
+++ b/bundle_header
@@ -10,19 +10,18 @@ EOF
 }
 
 die() {
-	echo "$@" >&2
-	exit 1
+    echo "$@" >&2
+    exit 1
 }
 
 cleanup() {
     if [ -e "$1" ]
     then
-
-        if [ -e "$(pwd)/.hsh" ]
-        then
-            rm -rf "$(pwd)/.hsh"
-        fi
-        rm -rf "$1"
+	if [ -e "$(pwd)/.hsh" ]
+	then
+	    rm -rf "$(pwd)/.hsh"
+	fi
+	# rm -rf "$1"
     fi
 }
 
@@ -36,46 +35,47 @@ run_hook() {
     [ -e "$tmp_dir/hooks/$1" ] || return
     if [ -e "$tmp_dir/dependencies/$1" ]
     then
-        while IFS= read -r entry
-        do
-            d="${entry%.git}"
-            d="${d%/}"
-            d="${d##*/}"
-            run_hook "$d"
-        done < "$tmp_dir/dependencies/$1"
+	while IFS= read -r entry
+	do
+	    d="${entry%.git}"
+	    d="${d%/}"
+	    d="${d##*/}"
+	    run_hook "$d"
+	done < "$tmp_dir/dependencies/$1"
     fi
     (
-        export HSH_ROOT="$(pwd)"
-    	export HSH_ACTION="bundle-out"
-    	export HSH_REPOSITORY="$1"
-    	export HSH_BUNDLE_ROOT="$tmp_dir/repos"
-        sh $tmp_dir/hooks/$1
+	export HSH_ROOT="$(pwd)"
+	export HSH_ACTION="bundle-out"
+	export HSH_REPOSITORY="$1"
+	export HSH_BUNDLE_ROOT="$tmp_dir/repos"
+	sh $tmp_dir/hooks/$1
     )
     rm "$tmp_dir/hooks/$1"
 }
 
 while [ $# -ne 0 ]
 do
-	case "$1" in
-		-h|--help)
-			usage
-            exit 0
-			;;
-        -C)
-            shift
-            [ $# -eq 0 ] && die "missing value for parameter '-C'"
-            dir="$1"
-            ;;
-		-b|--bin)
-			shift
-            [$tmp_dir/root $# -eq 0 ] && die "missing value for parameter --hsh-dir"
-			bin_dir="$1"
-			;;
-		*)
-			die "unknown option '$1'"
-			;;
-	esac
-	shift
+    case "$1" in
+	-h|--help)
+	    usage
+	    exit 0
+	    ;;
+	-C)
+	    shift
+	    [ $# -eq 0 ] && die "missing value for parameter '-C'"
+	    dir="$1"
+	    ;;
+	-b|--bin)
+	    shift
+	    [$tmp_dir/root $# -eq 0 ] && \
+		die "missing value for parameter --hsh-dir"
+	    bin_dir="$1"
+	    ;;
+	*)
+	    die "unknown option '$1'"
+	    ;;
+    esac
+    shift
 done
 
 if [ -n "${dir-}" ]
@@ -109,25 +109,31 @@ ls -1 "$tmp_dir/repos" | while IFS= read -r repo
 do
     if [ "$repo" = "hsh" ]
     then
-        fixup_worktree "$tmp_dir/repos/$repo/config" "$(pwd)/bin"
+	fixup_worktree "$tmp_dir/repos/$repo/config" "$(pwd)/bin"
     else
-        fixup_worktree "$tmp_dir/repos/$repo/config" "$(pwd)"
+	fixup_worktree "$tmp_dir/repos/$repo/config" "$(pwd)"
     fi
 done
 
 cp -rfP "$tmp_dir/repos" "$hsh_dir"
 
-ls -1 "$tmp_dir/root" | while IFS= read -r entry
+find "$tmp_dir/root" | while IFS= read -r entry
 do
-    cp -rfP "$tmp_dir/root/$entry" "$(pwd)"
+    dest="$(pwd)$(echo "$entry" | sed s,$tmp_dir/root,,)"
+    if [ -d "$entry" ]
+    then 
+	[ ! -d $dest ] && mkdir "$dest"
+    else
+	cp -fP "$entry" "$dest"
+    fi
 done
 
 while [ $(ls -1 "$tmp_dir/hooks" | wc -l) -ne 0 ]
 do
-	run_hook "$(ls -1 "$tmp_dir/hooks" | head -n 1)"
+    run_hook "$(ls -1 "$tmp_dir/hooks" | head -n 1)"
 done
 
-rm -rf "$tmp_dir"
+# rm -rf "$tmp_dir"
 
 exit $?
 
